# Generated by Django 4.2.28 on 2026-03-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberchoice',
            name='piece_identifier',
            field=models.CharField(blank=True, help_text="Stores selected piece identifier (e.g., 'robot_0', 'avatar', 'traditional_1')", max_length=50, null=True),
        ),
    ]
