# Generated by Django 4.2.28 on 2026-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehome', '0002_memberchoice_piece_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberchoice',
            name='choice',
            field=models.CharField(choices=[('Random', 'Random'), ('X', 'X'), ('O', 'O'), ('Selection', 'Selection')], default='Random', max_length=20),
        ),
    ]
