# Generated by Django 4.2.28 on 2026-03-17 11:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehome', '0004_alter_memberchoice_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberavatar',
            name='avatar_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='memberchoice',
            name='choice',
            field=models.CharField(choices=[('Standard', 'Standard (random within theme)'), ('Random', 'Global random (all themes)'), ('Selection', 'Selected from gallery')], default='Standard', max_length=20),
        ),
    ]
