# Generated by Django 4.2.28 on 2026-03-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamehome', '0005_alter_memberavatar_avatar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberavatar',
            name='avatar_public_id',
            field=models.CharField(blank=True, help_text="Cloudinary public_id for the user's avatar image (authenticated uploads)", max_length=255, null=True),
        ),
    ]
